# Generated by Django 5.1.4 on 2024-12-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_remove_book_available_book_copies_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies_available',
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_borrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='library_api.book')),
            ],
        ),
    ]
