# Generated by Django 5.1.4 on 2024-12-13 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_remove_book_copies_available_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_api.user'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
