# Generated by Django 5.1.4 on 2024-12-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0007_alter_borrowrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.user'),
        ),
    ]
